### ISSUE TITLE
Errors during starting Choreonoid project

### ISSUE THREAD

**Issue by kx-guan** [stephane-caron/lipm_walking_controller#46]
Hi, Dear Dr. Caron:

 Hope that you are fine.

 I have used the JVRC-1 project in mc_openrtm(https://github.com/jrl-umi3218/mc_openrtm.git) to try to run LIPM stablizer. But some problems occurred.

### Messages on Choreonoid:
```
==========================================
 .
 .
 .
プロジェクトファイル"sim_mc.cnoid"を読み込み中…
タスクシーケンサ '' が非活性化されました．
PythonPlugin: "/usr/local/lib/python2.7/dist-packages/hrpsys" がPythonのモジュールパスに追加されました．
ExtCommandItem "ModelLoader" を読み込み中
OpenGL version is 3.0.
GLSL version is 1.30.
外部コマンド"openhrp-model-loader"がアイテム"ModelLoader"によって実行されました．
WorldItem "World" を読み込み中
ready
BodyItem "JVRC1" を読み込み中
ボディ "/usr/local/share/OpenHRP-3.1/robot/JVRC1/main.wrl" を読み込み中
 -> 完了!
BodyRTCItem "BodyRTC" を読み込み中
設定ファイル "/usr/local/lib/choreonoid-1.7/rtc/Virtual-JVRC1-RTC.conf" が読み込まれました．
RTC "PDcontroller" を "/usr/local/lib/choreonoid-1.7/rtc/PDcontroller.so" から生成しました．
RTC "JVRC1Controller(Robot)0" を生成しました．
SensorVisualizer "SensorVisualizer" を読み込み中
loading 
 cannot be found.
Retrying to load the file as a standard VRML file
 cannot be found.
loading failed.
 cannot be found.
BodyItem "longfloor" を読み込み中
ボディ "/usr/local/share/OpenHRP-3.1/sample/model/longfloor.wrl" を読み込み中
 -> 完了!
AISTSimulatorItem "AISTSimulator" を読み込み中
PythonSimScriptItem "sim_mc.py" を読み込み中
シミュレーション用Pythonスクリプト "/usr/local/share/hrpsys/samples/JVRC1/sim_mc.py" を読み込み中
 -> 完了!
8 / 8 のアイテムが読みこまれました．
プロジェクト "sim_mc.cnoid" を完全に読み込みました．
RTコンポーネントの設定をしています．
実行コンテキストを取得しました．
接続 JVRC1Controller(Robot)0:q --> PDcontroller0:angle
接続に成功しました．
接続 JVRC1Controller(Robot)0:tau <-- PDcontroller0:torque
接続に成功しました．
AISTSimulatorによるシミュレーションを開始しました．
Pythonスクリプト "sim_mc.py" の実行を開始しました．
[rtm.py] nshost already set as localhost
[rtm.py] nsport already set as 2809
[rtm.py] Failed to parse corba.master_manager, use 2810
[rtm.py] configuration ORB with localhost:2809
[rtm.py] configuration RTCManager with localhost:2810
[rtm.py] trying to findRTCManager on port2810
[rtm.py] trying to findRTCManager on port2810
[rtm.py] trying to findRTCManager on port2810
[rtm.py] trying to findRTCManager on port2810
Manager not found
creating components
[rtm.py] trying to findRTCManager on port2810
[rtm.py] trying to findRTCManager on port2810
[rtm.py] trying to findRTCManager on port2810
[rtm.py] trying to findRTCManager on port2810
Manager not found
Pythonスクリプト "sim_mc.py" の実行に失敗しました．
Traceback (most recent call last):
  File "<string>", line 144, in <module>
  File "<string>", line 113, in init
  File "<string>", line 69, in createComps
AttributeError: 'NoneType' object has no attribute 'load'
============================
```

### Messages on terminal:

```
============================
choreonoid: オプションには引数が必要です -- 'f'
PDcontroller0: onInitialize() 
ModelLoaderException :  cannot be found.
[PDcontroller0] failed to load model[]
PDcontroller0: on Activated 
[PDcontroller0] Gain file [] not opened
[PDcontroller0] No pdcontrol_tlimit_ratio found.
[PDcontroller0] All tlimit_ratio are set to 1.0.
[PDcontroller0] loadGain
[PDcontroller0] m_robot is not set properly!! Maybe ModelLoader is missing?
[PDcontroller0] m_robot is not set properly!! Maybe ModelLoader is missing?
[PDcontroller0] m_robot is not set properly!! Maybe ModelLoader is missing?
============================
```

 I have investigated the error messages from the terminal, and found these were from the
the [PDcontroller] component of hrpsys-base. Then I changed "Virtual-JVRC1-RTC.conf" 
in sim_mc.cnoid to "PDcontroller.conf"(In mc_openrtm git, there is no "PDcontroller.conf", but there is a "PDcontroller.in.conf.choreonoid" file).
I replaced the "ffile:///@OPENHRP3_1_PREFIX@/share/OpenHRP-3.1/robot/JVRC1/main.wrl" to "/usr/local/share/OpenHRP-3.1/robot/JVRC1/main.wrl" in "PDcontroller.conf"
and then copied this to "/usr/local/lib/choreonoid-1.7/rtc/".
  But there are still errors as follows.

### Messages on Choreonoid:

```
==========================================
 .
 .
 .
プロジェクトファイル"sim_mc.cnoid"を読み込み中…
タスクシーケンサ '' が非活性化されました．
PythonPlugin: "/usr/local/lib/python2.7/dist-packages/hrpsys" がPythonのモジュールパスに追加されました．
ExtCommandItem "ModelLoader" を読み込み中
OpenGL version is 3.0.
GLSL version is 1.30.
外部コマンド"openhrp-model-loader"がアイテム"ModelLoader"によって実行されました．
WorldItem "World" を読み込み中
ready
BodyItem "JVRC1" を読み込み中
ボディ "/usr/local/share/OpenHRP-3.1/robot/JVRC1/main.wrl" を読み込み中
 -> 完了!
BodyRTCItem "BodyRTC" を読み込み中
"/usr/local/lib/choreonoid-1.7/rtc/PDcontroller.conf" は存在しないか，開けません．
RTC "PDcontroller" を "/usr/local/lib/choreonoid-1.7/rtc/PDcontroller.so" から生成しました．
RTC "JVRC1Controller(Robot)0" を生成しました．
SensorVisualizer "SensorVisualizer" を読み込み中
loading 
 cannot be found.
Retrying to load the file as a standard VRML file
 cannot be found.
loading failed.
 cannot be found.
BodyItem "longfloor" を読み込み中
ボディ "/usr/local/share/OpenHRP-3.1/sample/model/longfloor.wrl" を読み込み中
 -> 完了!
AISTSimulatorItem "AISTSimulator" を読み込み中
PythonSimScriptItem "sim_mc.py" を読み込み中
シミュレーション用Pythonスクリプト "/usr/local/share/hrpsys/samples/JVRC1/sim_mc.py" を読み込み中
 -> 完了!
8 / 8 のアイテムが読みこまれました．
プロジェクト "sim_mc.cnoid" を完全に読み込みました．
RTコンポーネントの設定をしています．
AISTSimulatorによるシミュレーションを開始しました．
Pythonスクリプト "sim_mc.py" の実行を開始しました．
[rtm.py] nshost already set as localhost
[rtm.py] nsport already set as 2809
[rtm.py] Failed to parse corba.master_manager, use 2810
[rtm.py] configuration ORB with localhost:2809
[rtm.py] configuration RTCManager with localhost:2810
[rtm.py] trying to findRTCManager on port2810
[rtm.py] trying to findRTCManager on port2810
[rtm.py] trying to findRTCManager on port2810
[rtm.py] trying to findRTCManager on port2810
Manager not found
creating components
[rtm.py] trying to findRTCManager on port2810
[rtm.py] trying to findRTCManager on port2810
[rtm.py] trying to findRTCManager on port2810
[rtm.py] trying to findRTCManager on port2810
Manager not found
Pythonスクリプト "sim_mc.py" の実行に失敗しました．
Traceback (most recent call last):
  File "<string>", line 144, in <module>
  File "<string>", line 113, in init
  File "<string>", line 69, in createComps
AttributeError: 'NoneType' object has no attribute 'load'
============================
```

### Messages on terminal:

```
============================
choreonoid: オプションには引数が必要です -- 'f'
PDcontroller0: onInitialize() 
ModelLoaderException :  cannot be found.
[PDcontroller0] failed to load model[]
============================
```

It seems that there are two problems:
1. Manager not found.
2. "PDcontroller.conf" exists, but it is still as follows:
 "/usr/local/lib/choreonoid-1.7/rtc/PDcontroller.conf" は存在しないか，開けません．

  I am puzzled. Could you give me any advice?
  Thank you very much.

**Comment by stephane-caron** [comment]
Hi @kx-guan. Your errors are related to the OpenRTM/Choreonoid configuration rather than to the LIPM walking controller itself. I'm not competent with OpenRTM/Choreonoid, so let me redirect your question to the experts in the Choreonoid project's issue tracker: 
https://github.com/jrl-umi3218/mc_openrtm/issues/4
